function removeEntryFromList() {}

const listOfNames = [
  "Dieter Bohlen",
  "Nena",
  "Roberto Blanco",
  "David Hasselhoff",
  "Wolfgang Petry",
  "Katja Krasavice",
  "Money Boy",
  "Bibis Beauty Palace",
  "Mickie Krause",
  "Ikke Hüftgold",
  "Beyonce",
  "Peter Maffay",
  "Jürgen Drews",
  "Helene Fischer",
  "Andrea Berg",
  "Rebecca Black",
  "Justin Bieber",
  "Modern Talking",
  "Nickelback",
  "Spice Girls",
  "Hans Zimmer",
  "Backstreet Boys",
  "Blue",
  "Enya",
  "Hollywood Undead",
  "Neffex",
  "Maradona",
  "Britney Spears",
  "Skrillex",
  "Scooter",
  "Faith +1",
  "Lorde",
];

const listOfSongs = [
  "Looking for Freedom",
  "I like my Burgers",
  "Vegan Superstar",
  "Ich bin ein Döner Remix",
  "Bier, den ganzen Tag",
  "Malle ist nur einmal im Jahr",
  "You're my Heart, You're My Soul",
  "Cheri Cheri Lady",
  "Macarena",
  "Who let the Dogs out",
  "Who let the Dieter Bohlen out",
  "Don't worry, be mad",
  "My Heart will go down",
  "Mambo No. 6",
  "Twilight is the best Love Movie Ever",
  "Crazy Frog, Jamba-Sparabo",
  "Baby, Hit me one more time",
  "Fortnite Battle Pass Song",
  "Oops! I did it again",
  "Atemlos durch die Nacht",
  "Frozen Neuinterpretation",
  "What does the Fox Say?",
  "Gangnam Style",
  "F steht für Freunde die was unternehmen",
  "Casa Bonita",
  "Remember the Name",
];

const listOfCountries = [
  "Serbia",
  "Portugal",
  "Albania",
  "Slovenia",
  "Switzerland",
  "Poland",
  "Moldova",
  "Spain",
  "France",
  "Austria",
  "Armenia",
  "Croatia",
  "Cyprus",
  "Lithuania",
  "Czechia",
  "Australia",
  "Estonia",
  "Belgium",
  "Ukraine",
  "Norway",
  "Italy",
  "Israel",
  "Finland",
  "Sweden",
  "Japan",
  "South Korea",
  "Iceland",
  "Latvia",
  "Georgia",
  "Greece",
  "Ireland",
  "Netherlands",
  "Denmark",
  "Azerbaijan",
  "Malta",
  "Romania",
  "San Marino",
  "Turkiye",
  "Russia",
];

const listOfSeededCountries = ["Germany", "United Kingdom"];

module.exports = {
  listOfNames,
  listOfSongs,
  listOfCountries,
  listOfSeededCountries,
};
