function removeEntryFromList() {}

const listOfNames = [
  "Dieter Bohlen",
  "Nena",
  "Roberto Blanco",
  "David Hasselhoff",
  "Wolfgang Petry",
  "Katja Krasavice",
  "Money Boy",
  "Bibis Beauty Palace",
  "Mickie Krause",
  "Ikke Hüftgold",
  "Beyonce",
  "Peter Maffay",
  "Jürgen Drews",
  "Helene Fischer",
  "Andrea Berg",
  "Rebecca Black",
  "Justin Bieber",
  "Modern Talking",
  "Nickelback",
  "Spice Girls",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
];

const listOfSongs = [
  "Looking for Freedom",
  "I like my Burgers",
  "Vegan Superstar",
  "Ich bin ein Döner Remix",
  "Bier, den ganzen Tag",
  "Malle ist nur einmal im Jahr",
  "You're my Heart, You're My Soul",
  "Cheri Cheri Lady",
  "Macarena",
  "Who let the Dogs out",
  "Who let the Dieter Bohlen out",
  "Don't worry, be mad",
  "My Heart will go down",
  "Mambo No. 6",
  "Twilight is the best Love Movie Ever",
  "Crazy Frog, Jamba-Sparabo",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
];

const listOfCountries = [
  "Germany",
  "United Kingdom",
  "Serbia",
  "Portugal",
  "Albania",
  "Slovenia",
  "Switzerland",
  "Poland",
  "Moldova",
  "Spain",
  "France",
  "Austria",
  "Armenia",
  "Croatia",
  "Cyprus",
  "Lithuania",
  "Czechia",
  "Australia",
  "Estonia",
  "Belgium",
  "Ukraine",
  "Norway",
  "Italy",
  "Israel",
  "Finland",
  "Sweden",
  "Japan",
  "South Korea",
  "Iceland",
  "Latvia",
  "Georgia",
  "Greece",
  "Ireland",
  "Netherlands",
  "Denmark",
  "Azerbaijan",
  "Malta",
  "Romania",
  "San Marino",
  "Turkiye",
  "Russia",
];

module.exports = { listOfNames, listOfSongs, listOfCountries };
